# Generated by Django 4.2 on 2023-05-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=30, verbose_name="Telefone")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
